'use strict';
module.exports = {
    opReturn: {
        opReturnPrefix: '6a',
        opReturnAppPrefixLength: '04',
        opPushDataOne: '4c',
        appPrefixes: {
            '00746162': 'Cashtab Msg',
            '65746162': 'Cashtab Encrypted',
            '2e786563': 'Alias',
            '46555a00': 'Cash Fusion',
            '64726f70': 'Airdrop',
            '53575000': 'Swap',
        },
        memo: {
            'prefix': '026d',
            'app': 'memo',
            '01': 'Set name',
            '02': 'Post memo',
            '03': 'Reply to memo',
            '04': 'Like / tip memo',
            '05': 'Set profile text',
            '06': 'Follow user',
            '07': 'Unfollow user',
            '0a': 'Set profile picture',
            '0b': 'Repost memo',
            '0c': 'Post topic message',
            '0d': 'Topic follow',
            '0e': 'Topic unfollow',
            '10': 'Create poll',
            '13': 'Add poll option',
            '14': 'Poll vote',
            '16': 'Mute user',
            '17': 'Unmute user',
            '24': 'Send money',
            '30': 'Sell tokens Spec',
            '31': 'Token buy offer Spec',
            '32': 'Attach token sale signature Spec',
            '35': 'Pin token post',
            '20': 'Link request',
            '21': 'Link accept',
            '22': 'Link revoke',
            '26': 'Set address alias',
        },
    },
};
